package app.guidecast.transmitter

import java.io.File
import java.io.RandomAccessFile
import java.math.BigDecimal
import java.security.MessageDigest
import java.util.Base64
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.withTimeout
import org.json.JSONObject

internal class TrialBlocked(val reasonCode: String) : IllegalStateException(reasonCode)
private fun JSONObject.trialFields(): Set<String> = keys().asSequence().toSet()
private class TrialFinished : CancellationException("TRIAL_EXPECTED_RESPONSES_COMPLETE")
internal fun trialDigest(value: String): String = MessageDigest.getInstance("SHA-256")
    .digest(value.toByteArray(Charsets.UTF_8)).joinToString("") { "%02x".format(it) }

/** Explicit operator approval is an input, not generated by the app. No embedded live permit.
 * The setup hash/token evidence must be reviewed before any connection; text counting is not guessed.
 */
internal class RestrictedTrialApproval private constructor(
    val reference: String, val expiresAtMillis: Long, val setupHash: String, val setupTokens: Int, val pcmHash: String,
) {
    companion object {
        fun read(values: Map<String, String>, nowMillis: Long): RestrictedTrialApproval? {
            if (values["paidTrialApproval"] != "APPROVED_GEMINI_3_8_LIVE_LIMITED_TRIAL_V1" ||
                values["approvedBudgetUsd"] != "0.50" || values["approvedModel"] != GEMINI_LIVE_AGENT ||
                values["approvedConnections"] != "2" || values["approvedResponses"] != "1,2" ||
                values["approvedSessionSeconds"] != "60" || values["approvedInputMillis"] != "38400" ||
                values["approvedOutputSecondsPerResponse"] != "20" || values["approvedOutputSecondsTotal"] != "60") return null
            val reference = values["approvalReference"]?.takeIf { it.matches(Regex("[A-Za-z0-9_-]{8,100}")) } ?: return null
            val expiry = values["approvalExpiresAtMillis"]?.toLongOrNull() ?: return null
            if (expiry <= nowMillis || expiry - nowMillis > 3_600_000) return null
            val hash = values["reviewedSetupSha256"]?.takeIf { it.matches(Regex("[0-9a-f]{64}")) } ?: return null
            val tokens = values["reviewedSetupTextTokens"]?.toIntOrNull()?.takeIf { it in 0..1024 } ?: return null
            val pcmHash = values["approvedPcmSha256"]?.takeIf { it.matches(Regex("[0-9a-f]{64}")) } ?: return null
            return RestrictedTrialApproval(reference, expiry, hash, tokens, pcmHash)
        }
    }
}

/** One approval can start one run only, even after test/process recreation. A crash consumes it.
 * Live callers must supply an app-private persistent filesDir path, not a disposable cache path.
 * The journal contains only digests, no credential or audio. Concurrent claims fail closed.
 */
internal class TrialPermitJournal(private val file: File) {
    @Synchronized fun consume(reference: String) {
        file.parentFile?.mkdirs()
        RandomAccessFile(file, "rw").use { data ->
            val lock = runCatching { data.channel.tryLock() }.getOrNull() ?: throw TrialBlocked("PERMIT_LOCKED")
            try {
                if (data.length() > 1_048_576) throw TrialBlocked("PERMIT_JOURNAL_FULL")
                val bytes = ByteArray(data.length().toInt()); data.readFully(bytes)
                val contents = bytes.toString(Charsets.UTF_8)
                if (contents.isNotEmpty() && (!contents.endsWith('\n') ||
                        contents.dropLast(1).lineSequence().any { !it.matches(Regex("[0-9a-f]{64}")) }))
                    throw TrialBlocked("PERMIT_JOURNAL_INVALID")
                val digest = trialDigest(reference)
                if (contents.lineSequence().any { it == digest }) throw TrialBlocked("APPROVAL_ALREADY_CONSUMED")
                data.seek(data.length()); data.write((digest + "\n").toByteArray()); data.fd.sync()
            } finally { lock.release() }
        }
    }
}

/** Test-only wire decorator. It never fetches a key; it passes the caller's existing opaque key
 * to the already selected app wire. Caps stop local work, not accrued/in-flight server billing.
 * Price snapshot: official Gemini pricing reviewed 2026-10-05, USD per million tokens.
 * Estimates intentionally do not subtract cache discounts or claim invoice equivalence.
 */
internal class RestrictedGeminiTrial(
    private val approval: RestrictedTrialApproval?, private val journal: TrialPermitJournal,
    private val reviewedSetup: String,
    approvedPreparedPcm: ByteArray,
    private val nowMillis: () -> Long = System::currentTimeMillis,
    private val nowNanos: () -> Long = System::nanoTime,
) {
    private val preparedPcm = approvedPreparedPcm.copyOf()
    private var permitConsumed = false
    private var active = false
    private var attempts = 0
    private var completedSessions = 0
    private var totalInputBytes = 0L
    private var totalOutputBytes = 0L
    private var estimatedUsd = BigDecimal.ZERO
    private var blocked: String? = null
    private val sessionReceipts = mutableListOf<JSONObject>()
    private val stopEstimate = BigDecimal("0.10")
    private fun deny(reason: String): Nothing { blocked = reason; throw TrialBlocked(reason) }
    @Synchronized private fun begin(): Int {
        val permit = approval ?: deny("EXPLICIT_APPROVAL_MISSING")
        if (blocked != null) throw TrialBlocked(requireNotNull(blocked))
        if (nowMillis() >= permit.expiresAtMillis) deny("APPROVAL_EXPIRED")
        if (trialDigest(reviewedSetup) != permit.setupHash || permit.setupTokens !in 0..1024) deny("SETUP_EVIDENCE_MISMATCH")
        validateSetup(reviewedSetup)
        if (preparedPcm.isEmpty() || preparedPcm.size > 409_600 || preparedPcm.size % 3200 != 0 ||
            MessageDigest.getInstance("SHA-256").digest(preparedPcm).joinToString("") { "%02x".format(it) } != permit.pcmHash)
            deny("UNAPPROVED_OR_UNALIGNED_PREPARED_PCM")
        if (active || attempts != completedSessions) deny("CONCURRENT_OR_FAILED_ATTEMPT")
        if (attempts >= 2) deny("CONNECTION_LIMIT")
        if (estimatedUsd >= stopEstimate) deny("ESTIMATE_STOP_THRESHOLD")
        if (!permitConsumed) { journal.consume(permit.reference); permitConsumed = true }
        active = true; attempts++
        return attempts // session1 permits1 response; session2 permits2
    }
    private fun validateSetup(raw: String) {
        val root = JSONObject(raw)
        if (root.trialFields() != setOf("setup")) deny("SETUP_SHAPE")
        val s = root.getJSONObject("setup")
        val allowed = setOf("model", "generationConfig", "systemInstruction", "inputAudioTranscription", "outputAudioTranscription")
        if (!allowed.containsAll(s.trialFields()) || s.getString("model") != "models/$GEMINI_LIVE_AGENT") deny("SETUP_TOOLS_RESUMPTION_OR_MODEL")
        val g = s.getJSONObject("generationConfig")
        if (g.trialFields() != setOf("responseModalities", "maxOutputTokens") || strictNumber(g, "maxOutputTokens") != 2048L ||
            g.getJSONArray("responseModalities").toString() != "[\"AUDIO\"]") deny("OUTPUT_TOKEN_OR_MODALITY_LIMIT")
    }
    private fun strictNumber(row: JSONObject, key: String): Long {
        val value = row.opt(key)
        if (value !is Number || value is Double || value is Float) deny("USAGE_MISSING_OR_NONINTEGER")
        val n = value.toString().toLongOrNull() ?: deny("USAGE_OUT_OF_RANGE")
        if (n !in 0..1_000_000) deny("USAGE_OUT_OF_RANGE")
        return n
    }
    private fun modalities(usage: JSONObject, field: String): Pair<Long, Long> {
        val list = usage.optJSONArray(field) ?: deny("USAGE_MODALITIES_UNKNOWN")
        val values = mutableMapOf<String, Long>()
        for (i in 0 until list.length()) {
            val row = list.getJSONObject(i); val kind = row.getString("modality")
            if (kind !in setOf("AUDIO", "TEXT") || values.put(kind, strictNumber(row, "tokenCount")) != null) deny("USAGE_MODALITY_ANOMALY")
        }
        return (values["AUDIO"] ?: deny("USAGE_AUDIO_UNKNOWN")) to (values["TEXT"] ?: deny("USAGE_TEXT_UNKNOWN"))
    }
    @Synchronized fun countsOnly(): JSONObject = JSONObject().put("connection_attempts", attempts)
        .put("completed_sessions", completedSessions).put("active", active).put("input_bytes", totalInputBytes)
        .put("output_bytes", totalOutputBytes).put("estimated_usd", estimatedUsd.toPlainString())
        .put("estimate_not_invoice_or_hard_cap", true).put("blocked_reason", blocked ?: JSONObject.NULL)
        .put("price_version", "GEMINI_LIVE_OFFICIAL_2026-10-05").put("sessions", org.json.JSONArray(sessionReceipts))

    fun wrap(existingAppWire: GeminiLiveWire): GeminiLiveWire = object : GeminiLiveWire {
        override suspend fun connect(key: String, authorized: () -> Boolean, block: suspend (RealtimeSocket) -> Unit) {
            fun checkPermission() = synchronized(this@RestrictedGeminiTrial) {
                if (!authorized()) deny("AUTHORIZATION_REVOKED")
                blocked?.let { throw TrialBlocked(it) }
            }
            val expectedResponses = try { checkPermission(); begin() } catch (failure: TrialBlocked) { throw failure }
                catch (_: Exception) { throw TrialBlocked("PREFLIGHT_FAILED") }
            var successful = false
            val session = Session(expectedResponses)
            try {
                // Starts BEFORE delegate.connect: includes handshake/setup and every blocking send/receive.
                withTimeout(minOf(60_000L, requireNotNull(approval).expiresAtMillis - nowMillis())) {
                  coroutineScope {
                    val revocation = launch {
                        while (isActive) { checkPermission(); delay(25) }
                    }
                    try {
                    existingAppWire.connect(key, authorized) { socket ->
                        try {
                            block(object : RealtimeSocket {
                                override suspend fun send(text: String) {
                                    checkPermission()
                                    synchronized(this@RestrictedGeminiTrial) { session.send(text) }
                                    socket.send(text)
                                    if (synchronized(this@RestrictedGeminiTrial) { session.needsEndSignal() }) {
                                        checkPermission()
                                        // Explicit stream end, never an appended silence/audio tail.
                                        socket.send("""{"realtimeInput":{"audioStreamEnd":true}}""")
                                    }
                                }
                                override suspend fun receive(): String {
                                    checkPermission()
                                    val remaining = synchronized(this@RestrictedGeminiTrial) {
                                        if (session.readyToClose()) throw TrialFinished()
                                        session.remainingUsageMillis()
                                    }
                                    val raw = if (remaining != null) withTimeout(remaining) { socket.receive() } else socket.receive()
                                    checkPermission()
                                    synchronized(this@RestrictedGeminiTrial) {
                                        // Reject even a buffered/late result delivered at or after the deadline.
                                        session.remainingUsageMillis()
                                        session.receive(raw)
                                    }
                                    return raw
                                }
                            })
                        } catch (_: TrialFinished) { successful = true }
                    }
                    } finally { revocation.cancel() }
                  }
                }
            } catch (failure: TrialBlocked) { throw failure
            } catch (_: CancellationException) { throw CancellationException("TRIAL_CANCELLED_OR_TIMED_OUT")
            } catch (_: Exception) { throw TrialBlocked("TRANSPORT_OR_PROTOCOL_FAILED")
            } finally {
                synchronized(this@RestrictedGeminiTrial) {
                    active = false
                    if (successful && blocked == null && session.readyToClose()) completedSessions++
                    else if (blocked == null) blocked = "SESSION_INCOMPLETE_TIMEOUT_CANCEL_OR_USAGE_UNKNOWN"
                    sessionReceipts += session.receipt()
                }
            }
        }
    }

    private inner class Session(private val expected: Int) {
        private var setupSent = false
        private var acknowledged = false
        private var responseOpen = false
        private var finished = 0
        private var terminalUsageDeadlineNanos: Long? = null
        private var outputThisResponse = 0L
        private var inputThisSession = 0L
        private var endSignals = 0
        private val usageConfirmed = mutableSetOf<Int>()
        private val usageSignatures = mutableSetOf<String>()
        private val transcriptions = JSONObject(reviewedSetup).getJSONObject("setup").let {
            it.has("inputAudioTranscription") || it.has("outputAudioTranscription") }
        private var transcriptionBillingUnknown = false
        fun allResponsesFinished() = finished == expected
        fun remainingUsageMillis(): Long? {
            val deadline = terminalUsageDeadlineNanos ?: return null
            val remaining = deadline - nowNanos()
            if (remaining <= 0L) throw CancellationException("TERMINAL_USAGE_DEADLINE")
            return (remaining + 999_999L) / 1_000_000L
        }
        fun readyToClose() = inputThisSession == expected * preparedPcm.size.toLong() && finished == expected && usageConfirmed.size == expected && !responseOpen && !transcriptionBillingUnknown
        fun needsEndSignal(): Boolean {
            if (inputThisSession > 0 && inputThisSession == (endSignals + 1) * preparedPcm.size.toLong()) {
                endSignals++; return true
            }
            return false
        }
        fun send(raw: String) {
            if (blocked != null) throw TrialBlocked(requireNotNull(blocked))
            if (nowMillis() >= requireNotNull(approval).expiresAtMillis) deny("APPROVAL_EXPIRED")
            if (raw.length > 262_144) deny("CLIENT_MESSAGE_LIMIT")
            if (!setupSent) {
                if (raw != reviewedSetup) deny("SETUP_CHANGED")
                setupSent = true; return
            }
            val root = JSONObject(raw)
            if (!acknowledged || root.trialFields() != setOf("realtimeInput")) deny("NON_AUDIO_OR_BEFORE_ACK")
            val realtime = root.getJSONObject("realtimeInput")
            if (allResponsesFinished() || realtime.trialFields() != setOf("audio")) deny("EXTRA_INPUT_OR_TOOL_TEXT")
            val audio = realtime.getJSONObject("audio")
            if (audio.trialFields() != setOf("mimeType", "data") || audio.getString("mimeType") != "audio/pcm;rate=16000") deny("INPUT_FORMAT")
            val bytes = Base64.getDecoder().decode(audio.getString("data")); val n = bytes.size
            if (n <= 0 || n % 2 != 0 || n > 3200) deny("INPUT_PACKET_LIMIT")
            if (inputThisSession + n > expected * 409_600L || totalInputBytes + n > 1_228_800L) deny("INPUT_DURATION_LIMIT")
            if (inputThisSession + n > expected * preparedPcm.size.toLong()) deny("UNPLANNED_ADDITIONAL_INPUT")
            for (i in bytes.indices) if (bytes[i] != preparedPcm[((inputThisSession + i) % preparedPcm.size).toInt()])
                deny("INPUT_DIFFERS_FROM_APPROVED_PCM")
            inputThisSession += n; totalInputBytes += n
        }
        fun receive(raw: String) {
            if (raw.length > 262_144) deny("SERVER_MESSAGE_LIMIT")
            val root = JSONObject(raw)
            if (!setOf("setupComplete", "serverContent", "usageMetadata").containsAll(root.trialFields())) deny("SERVER_TOOL_RESUME_ERROR_OR_UNKNOWN")
            if (root.has("setupComplete")) {
                if (!setupSent || acknowledged) deny("DUPLICATE_OR_EARLY_ACK")
                acknowledged = true
            }
            val content = root.optJSONObject("serverContent")
            val complete = content?.optBoolean("turnComplete", false) == true
            if (content != null) {
                if (!setOf("modelTurn", "turnComplete", "generationComplete", "inputTranscription", "outputTranscription",
                        "interrupted", "turnCompleteReason", "waitingForInput").containsAll(content.trialFields())) deny("SERVER_CONTENT_UNKNOWN")
                if (!acknowledged || content.optBoolean("interrupted", false)) deny("INTERRUPTION_OR_BEFORE_ACK")
                val parts = content.optJSONObject("modelTurn")?.optJSONArray("parts")
                val outputPresent = parts != null || content.has("outputTranscription") || complete
                if (outputPresent && !responseOpen) {
                    if (finished >= expected) deny("UNEXPECTED_RESPONSE")
                    responseOpen = true; outputThisResponse = 0
                }
                if (parts != null) for (i in 0 until parts.length()) {
                    val part = parts.getJSONObject(i)
                    if (part.trialFields() != setOf("inlineData")) deny("NON_AUDIO_GENERATION")
                    val blob = part.getJSONObject("inlineData")
                    if (blob.trialFields() != setOf("mimeType", "data") || blob.getString("mimeType") !in setOf("audio/pcm;rate=24000", "audio/pcm;rate=24000;channels=1")) deny("OUTPUT_FORMAT")
                    val n = Base64.getDecoder().decode(blob.getString("data")).size
                    if (n <= 0 || n % 2 != 0 || n > 96_000) deny("OUTPUT_PACKET_LIMIT")
                    if (outputThisResponse + n > 960_000 || totalOutputBytes + n > 2_880_000) deny("OUTPUT_DURATION_LIMIT")
                    outputThisResponse += n; totalOutputBytes += n
                }
            }
            root.optJSONObject("usageMetadata")?.let { usage ->
                val response = if (responseOpen) finished + 1 else finished
                if (response <= 0) deny("USAGE_RESPONSE_UNKNOWN")
                val prompt = strictNumber(usage, "promptTokenCount")
                val output = strictNumber(usage, "responseTokenCount")
                val total = strictNumber(usage, "totalTokenCount")
                val cached = strictNumber(usage, "cachedContentTokenCount")
                val thought = strictNumber(usage, "thoughtsTokenCount")
                val tools = strictNumber(usage, "toolUsePromptTokenCount")
                val inputModalities = modalities(usage, "promptTokensDetails")
                val outputModalities = modalities(usage, "responseTokensDetails")
                if (tools != 0L || cached > prompt || prompt + output != total || output > 2048 ||
                    inputModalities.first + inputModalities.second != prompt || outputModalities.first + outputModalities.second != output)
                    deny("USAGE_TOTAL_OR_TOKEN_LIMIT_ANOMALY")
                // Separate transcription billing coverage is not established by these fields.
                // Do not substitute zero for that unknown; a live transcription trial cannot open session2 yet.
                if (transcriptions) transcriptionBillingUnknown = true
                val signature = "$response:$prompt:$output:$total:$cached:$thought:$tools:$inputModalities:$outputModalities"
                if (usageSignatures.add(signature)) {
                    if (usageSignatures.size > 32) deny("USAGE_EVENT_LIMIT")
                    // Cache is INCLUDED in prompt. Charge full input, not prompt+cache.
                    // Counting thought separately may overestimate; never label this a billed total.
                    val dollarsPerMillion = BigDecimal(inputModalities.first).multiply(BigDecimal("3.00"))
                        .add(BigDecimal(inputModalities.second).multiply(BigDecimal("0.75")))
                        .add(BigDecimal(outputModalities.first).multiply(BigDecimal("12.00")))
                        .add(BigDecimal(outputModalities.second + thought).multiply(BigDecimal("4.50")))
                    estimatedUsd = estimatedUsd.add(dollarsPerMillion.movePointLeft(6))
                    if (estimatedUsd >= stopEstimate) deny("ESTIMATE_STOP_THRESHOLD")
                }
                if (complete || !responseOpen) usageConfirmed += response
            }
            if (complete) {
                if (!responseOpen || outputThisResponse == 0L) deny("EMPTY_OR_DUPLICATE_TURN_COMPLETE")
                responseOpen = false; finished++
                // Latch once at final completion; control messages never refresh this grace.
                if (allResponsesFinished() && terminalUsageDeadlineNanos == null)
                    terminalUsageDeadlineNanos = nowNanos() + 1_000_000_000L
            }
        }
        fun receipt() = JSONObject().put("expected_responses", expected).put("finished_responses", finished)
            .put("input_bytes", inputThisSession).put("confirmed_usage_responses", usageConfirmed.size)
            .put("transcription_cost_coverage", if (transcriptionBillingUnknown) "UNKNOWN" else if (transcriptions) "UNOBSERVED" else "DISABLED")
            .put("usage_may_include_rebilled_context", true).put("estimate_not_invoice", true)
    }
}
