package app.guidecast.transmitter

/**
 * Human-readable inventory for production dependencies, toolchain components, and downloaded
 * model families. License texts and upstream notices that may be redistributed are packaged as
 * offline assets; current service terms remain linked to their authoritative publisher.
 */
internal enum class LicenseCategory(val displayName: String) {
    APP_LIBRARY("앱 라이브러리"),
    AI_RUNTIME("AI 실행 구성"),
    MODEL_AND_VOICE("모델·음성"),
    BUILD_AND_TEST("빌드·시험 도구"),
}

internal data class ThirdPartyLicenseEntry(
    val id: String,
    val name: String,
    val packageName: String,
    val version: String,
    val licenseName: String,
    val category: LicenseCategory,
    val notice: String,
    val sourceUrl: String,
    val offlineDocumentAsset: String? = null,
)

internal const val GUIDECAST_DEVELOPER_CONTACT = "dash.jeong@gmail.com"
internal const val GUIDECAST_PRODUCT_ATTRIBUTION = "Powered by Codex, Gemini with dash.jeong"
internal const val MOONSHINE_REQUIRED_ATTRIBUTION = "Powered by Moonshine AI"

internal val GUIDECAST_LICENSE_CATALOG: List<ThirdPartyLicenseEntry> = listOf(
    ThirdPartyLicenseEntry(
        id = "rnnoise", name = "RNNoise AI 마이크 소음 감소", packageName = "libguidecast_rnnoise.so",
        version = "0.2 · model 0b50c45", licenseName = "BSD 3-Clause", category = LicenseCategory.AI_RUNTIME,
        notice = "오프라인 CPU 신경망 소음 감소. 마이크 입력에만 선택 적용하며 번역·TTS·앱 재생음은 가공하지 않습니다.",
        sourceUrl = "https://github.com/xiph/rnnoise",
        offlineDocumentAsset = "licenses/RNNOISE-BSD-3-CLAUSE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "nikl-public-terminology",
        name = "국립국어원 공공언어 통합 지원 시스템 및 공공용어 번역 자료",
        packageName = "assets/glossary/public-20260905.db",
        version = "공공용어 번역 통합 데이터 (국립국어원 연계 안내)",
        licenseName = "공공데이터 이용조건 (출처 표시 / 출처기관별 조건 안내)",
        category = LicenseCategory.APP_LIBRARY,
        notice = "국립국어원 공공언어 통합 지원 시스템(https://publang.korean.go.kr) 및 공식 누리집(https://www.korean.go.kr)에서 제공하는 공공용어 표준 번역 자료(서울시·한국관광공사·외교부·행정안전부 통합)를 연계 및 안내합니다. 최신 표준 번역어 조회 및 공식 감수 정보는 국립국어원 누리집을 통해 직접 확인하실 수 있습니다. 사용자 수정은 기기 내부에만 보관되며 공식 번역을 대신하지 않습니다.",
        sourceUrl = "https://publang.korean.go.kr",
        offlineDocumentAsset = "licenses/PUBLIC-TERMINOLOGY-NOTICES.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "mcasttalk-first-party-license",
        name = "MCastTalk 독자 소스 라이선스",
        packageName = "app.guidecast.transmitter",
        version = "${BuildConfig.VERSION_NAME}",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "Copyright 2026 dash.jeong. MCastTalk 자체 작성 소스는 Apache License 2.0에 따라 상업적 이용을 포함한 사용·수정·재배포가 허용됩니다. 저작권·라이선스·필요한 고지를 유지하세요. 제3자 구성요소에는 각각의 조건이 적용됩니다. 이 라이선스는 MCastTalk 상표·로고의 제품 브랜드 사용이나 공식 제휴·보증 표시를 허가하지 않습니다. 그러한 사용의 허가는 dash.jeong@gmail.com으로 문의하세요. 정당한 출처 표시·사실 설명과 독립적인 서비스 구현에는 별도 협의를 요구하지 않습니다.",
        sourceUrl = "https://www.apache.org/licenses/LICENSE-2.0",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "mcasttalk-third-party-notices",
        name = "MCastTalk 제3자 고지 색인",
        packageName = "APK assets/licenses",
        version = "${BuildConfig.VERSION_NAME}",
        licenseName = "구성별 라이선스·이용조건",
        category = LicenseCategory.APP_LIBRARY,
        notice = "이 APK에 포함된 라이선스 전문, 모델·음성 고지와 공식 AAR 제3자 고지의 오프라인 색인입니다.",
        sourceUrl = "https://github.com/dashjeong/MCastTalk",
        offlineDocumentAsset = "licenses/THIRD-PARTY-NOTICES.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "opencc-dictionary-data",
        name = "Open Chinese Convert (OpenCC) 번체 변환 사전",
        packageName = "core/translation (내장 사전 데이터)",
        version = "revision 26753884f1984add422f3b0249ccee8613deaff6",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "간체→대만 번체(s2twp) 변환에 사용되는 문자 2,871자, 어휘 9,796개 변환 데이터입니다. Apache-2.0 라이선스가 적용됩니다.",
        sourceUrl = "https://github.com/BYVoid/OpenCC",
        offlineDocumentAsset = "licenses/OPENCC-APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "androidx-core",
        name = "AndroidX Core KTX",
        packageName = "androidx.core:core-ktx",
        version = "1.17.0",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "Android 호환 API와 Kotlin 확장 기능을 사용합니다.",
        sourceUrl = "https://github.com/androidx/androidx",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "androidx-activity",
        name = "AndroidX Activity Compose",
        packageName = "androidx.activity:activity-compose",
        version = "1.11.0",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "Compose 화면 수명주기와 Activity 결과 API를 사용합니다.",
        sourceUrl = "https://github.com/androidx/androidx",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "androidx-lifecycle",
        name = "AndroidX Lifecycle",
        packageName = "runtime-ktx · runtime-compose · viewmodel-compose",
        version = "2.9.4",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "화면 상태와 ViewModel 수명주기를 관리합니다.",
        sourceUrl = "https://github.com/androidx/androidx",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "androidx-state-support",
        name = "AndroidX 상태·컬렉션 지원",
        packageName = "androidx.savedstate:savedstate-* · androidx.collection:collection-*",
        version = "SavedState 1.3.1 · Collection 1.5.0",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "화면 상태 저장과 AndroidX 컬렉션 전이 런타임입니다.",
        sourceUrl = "https://github.com/androidx/androidx",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "compose",
        name = "Jetpack Compose Material 3",
        packageName = "Compose BOM · ui · foundation · material3",
        version = "BOM 2025.08.00 · UI 1.9.0 · Material3 1.3.2",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "운영자 화면과 접근 가능한 Material 컴포넌트를 구성합니다.",
        sourceUrl = "https://github.com/androidx/androidx",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "androidx-storage-work",
        name = "AndroidX 저장·백그라운드 작업",
        packageName = "androidx.work:work-runtime · androidx.room:room-* · androidx.sqlite:sqlite-*",
        version = "Work 2.9.1 · Room 2.5.0 · SQLite 2.3.0",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "ML Kit 전이 경로가 사용하는 작업 예약, 내부 상태 저장과 SQLite 지원 런타임입니다.",
        sourceUrl = "https://github.com/androidx/androidx",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "androidx-ui-transitive",
        name = "AndroidX UI 전이 런타임",
        packageName = "AppCompat · Material Components · Fragment · RecyclerView 및 AndroidX 지원 모듈",
        version = "AppCompat 1.6.1 · Material Components 1.10.0 · 세부 버전은 상세 고지 참조",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "annotation-experimental 1.4.1, annotation-jvm 1.9.1, arch-core 2.2.0, autofill/cardview 1.0.0, concurrent-futures 1.1.0, constraintlayout 2.0.1, coordinatorlayout 1.1.0, core-viewtree 1.0.0, cursoradapter 1.0.0, customview 1.1.0, customview-poolingcontainer 1.0.0, documentfile 1.0.0, drawerlayout 1.1.1, dynamicanimation 1.0.0, emoji2 1.4.0, fragment 1.3.6, graphics-path 1.0.1, interpolator/loader/localbroadcastmanager/print 1.0.0, legacy-support-core-utils 1.0.0, profileinstaller 1.4.0, recyclerview 1.1.0, resourceinspection-annotation 1.0.1, startup-runtime 1.1.1, tracing 1.2.0, transition 1.2.0, vectordrawable 1.1.0, versionedparcelable 1.1.1, viewpager/viewpager2 1.0.0이 해석됩니다.",
        sourceUrl = "https://github.com/androidx/androidx",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "coroutines",
        name = "Kotlinx Coroutines",
        packageName = "org.jetbrains.kotlinx:kotlinx-coroutines-core/android",
        version = "1.11.0 (최종 런타임 해석)",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "오디오·번역·네트워크 작업의 취소 가능한 비동기 처리를 담당합니다.",
        sourceUrl = "https://github.com/Kotlin/kotlinx.coroutines",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "kotlin-runtime",
        name = "Kotlin Runtime",
        packageName = "org.jetbrains.kotlin:kotlin-stdlib · kotlin-reflect",
        version = "2.3.21",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "APK에 포함된 Kotlin 표준 라이브러리와 리플렉션 런타임입니다.",
        sourceUrl = "https://github.com/JetBrains/kotlin",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "kotlin-compat-runtime",
        name = "Kotlin JDK 호환 모듈",
        packageName = "org.jetbrains.kotlin:kotlin-stdlib-jdk7 · kotlin-stdlib-jdk8",
        version = "1.9.10 (빈 호환 모듈)",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "최종 dependency graph에 남는 빈 JDK 7/8 호환 좌표이며 실행 코드는 Kotlin 2.3.21 표준 라이브러리로 통합됩니다.",
        sourceUrl = "https://github.com/JetBrains/kotlin",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "ktor",
        name = "Ktor Server",
        packageName = "io.ktor:ktor-server-core/cio/websockets/body-limit",
        version = "3.5.2",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "핫스팟 안의 로컬 웹 페이지와 WebSocket 음성 서버를 제공합니다.",
        sourceUrl = "https://github.com/ktorio/ktor",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "zxing",
        name = "ZXing Core",
        packageName = "com.google.zxing:core",
        version = "3.5.3",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "청취 페이지 접속 QR 코드를 생성합니다.",
        sourceUrl = "https://github.com/zxing/zxing",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "runtime-support",
        name = "직렬화·설정·입출력 런타임",
        packageName = "Typesafe Config · kotlinx-serialization · kotlinx-io",
        version = "1.4.9 · 1.11.0 · 0.9.1",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.APP_LIBRARY,
        notice = "Ktor와 앱 런타임이 실제로 해석한 지원 패키지입니다.",
        sourceUrl = "https://github.com/lightbend/config",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "slf4j",
        name = "SLF4J",
        packageName = "org.slf4j:slf4j-api",
        version = "2.0.18",
        licenseName = "MIT License",
        category = LicenseCategory.APP_LIBRARY,
        notice = "Ktor의 로깅 API 런타임입니다. 고정 버전의 저작권·허가문을 APK에 포함합니다.",
        sourceUrl = "https://github.com/qos-ch/slf4j/blob/v_2.0.18/LICENSE.txt",
        offlineDocumentAsset = "licenses/SLF4J-2.0.18-LICENSE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "mlkit-translate",
        name = "Google ML Kit Translation",
        packageName = "com.google.mlkit:translate · com.google.mlkit:common",
        version = "Translate 17.0.3 · Common 18.11.0",
        licenseName = "Google ML Kit Terms · Google APIs Terms",
        category = LicenseCategory.AI_RUNTIME,
        notice = "경량 온디바이스 번역 경로입니다. 오픈소스 라이선스가 아니라 Google ML Kit Terms와 그 약관에 통합된 Google APIs Terms가 적용됩니다.",
        sourceUrl = "https://developers.google.com/ml-kit/terms",
        offlineDocumentAsset = "licenses/upstream/third_party_licenses.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "google-apis-terms",
        name = "Google APIs Terms",
        packageName = "Google ML Kit API 사용 조건",
        version = "현재 온라인 약관 · 출시 시 재확인",
        licenseName = "Google APIs Terms of Service",
        category = LicenseCategory.AI_RUNTIME,
        notice = "ML Kit Terms가 통합 참조하는 현재 서비스 약관입니다. 변경 가능한 약관이므로 APK에 정적 전문을 복제하지 않고 공식 HTTPS 페이지를 엽니다.",
        sourceUrl = "https://developers.google.com/terms",
    ),
    ThirdPartyLicenseEntry(
        id = "mlkit-runtime-notices",
        name = "ML Kit 포함 런타임 고지",
        packageName = "OkHttp · Okio · Gson · Google Data Transport · Firebase Components/Encoders · 지원 annotation",
        version = "OkHttp 4.12.0 · Okio 3.6.0 · Gson 2.13.2 · Transport 2.2.1/2.3.3/2.2.6 · Firebase 16.1.0/17.1.0",
        licenseName = "ML Kit AAR 공식 제3자 고지 참조",
        category = LicenseCategory.AI_RUNTIME,
        notice = "ML Kit Translate 17.0.3 AAR가 제공하는 제3자 라이선스 전문을 빌드 시 그대로 추출해 APK에 포함합니다. transport-api 2.2.1, transport-backend-cct 2.3.3, transport-runtime 2.2.6, firebase-annotations 16.0.0, firebase-components/encoders 16.1.0, firebase-encoders-json 17.1.0, error_prone_annotations 2.41.0, listenablefuture 1.0, javax.inject 1, JetBrains annotations 23.0.0, jspecify 1.0.0이 해석됩니다.",
        sourceUrl = "https://developers.google.com/ml-kit/terms",
        offlineDocumentAsset = "licenses/upstream/third_party_licenses.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "google-play-services-runtime",
        name = "Google Play services 지원 런타임",
        packageName = "play-services-base · basement · tasks",
        version = "18.5.0 · 18.4.0 · 18.2.0",
        licenseName = "Android Software Development Kit License Agreement",
        category = LicenseCategory.AI_RUNTIME,
        notice = "ML Kit가 사용하는 Google Play services 지원 구성입니다. 현재 약관은 공식 Android SDK 페이지에서 확인합니다.",
        sourceUrl = "https://developer.android.com/studio/terms.html",
    ),
    ThirdPartyLicenseEntry(
        id = "litert-lm",
        name = "LiteRT-LM Android",
        packageName = "com.google.ai.edge.litertlm:litertlm-android",
        version = "0.16.1",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Gemma 4 E2B를 기기 안에서 실행하는 런타임입니다. 모델 이용조건은 별도입니다.",
        sourceUrl = "https://github.com/google-ai-edge/LiteRT-LM",
        offlineDocumentAsset = "licenses/upstream/THIRD_PARTY_NOTICE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-voice",
        name = "Moonshine Voice Android",
        packageName = "ai.moonshine:moonshine-voice",
        version = "0.1.5",
        licenseName = "MIT (소프트웨어) · 모델/데이터별 조건",
        category = LicenseCategory.AI_RUNTIME,
        notice = "음성인식·다국어 TTS 실행 SDK입니다. SDK 코드는 MIT이지만 한국어 legacy non-streaming TINY와 TTS/G2P 데이터에는 별도 조건이 적용됩니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/LICENSE",
        offlineDocumentAsset = "licenses/MOONSHINE-0.1.5-LICENSE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-required-notice",
        name = "Moonshine AI 필수 Notice",
        packageName = "Korean legacy non-streaming TINY STT",
        version = "Moonshine Voice 0.1.5",
        licenseName = "Moonshine AI Community License attribution",
        category = LicenseCategory.AI_RUNTIME,
        notice = "필수 attribution, 적용 모델과 GuideCast 통합 변경 범위를 오프라인으로 제공합니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/LICENSE",
        offlineDocumentAsset = "licenses/MOONSHINE-NOTICE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "onnx-runtime",
        name = "Microsoft ONNX Runtime Android",
        packageName = "com.microsoft.onnxruntime:onnxruntime-android",
        version = "1.23.2",
        licenseName = "MIT License",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine Kokoro 모델에 필요한 ARM64 연산 런타임을 수정 없이 포함합니다.",
        sourceUrl = "https://github.com/microsoft/onnxruntime/blob/v1.23.2/LICENSE",
        offlineDocumentAsset = "licenses/MIT.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "onnx-runtime-third-party-notices",
        name = "ONNX Runtime 제3자 소프트웨어 고지",
        packageName = "com.microsoft.onnxruntime:onnxruntime-android",
        version = "1.23.2 · upstream tag v1.23.2",
        licenseName = "구성요소별 제3자 라이선스",
        category = LicenseCategory.AI_RUNTIME,
        notice = "APK에 포함된 ONNX Runtime ARM64 바이너리의 공식 버전 고정 ThirdPartyNotices 전문입니다.",
        sourceUrl = "https://github.com/microsoft/onnxruntime/blob/v1.23.2/ThirdPartyNotices.txt",
        offlineDocumentAsset = "licenses/ONNXRUNTIME-1.23.2-THIRD-PARTY-NOTICES.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-eigen",
        name = "Moonshine native · Eigen",
        packageName = "core/third-party/Eigen",
        version = "3.4.0 · Moonshine 0.1.5 vendored subset",
        licenseName = "Mozilla Public License 2.0",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine 네이티브 음성 런타임에 포함된 선형대수 구성입니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/core/third-party/Eigen/COPYING.MPL2",
        offlineDocumentAsset = "licenses/MOONSHINE-EIGEN-MPL-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-kaldi-fbank",
        name = "Moonshine native · kaldi-native-fbank",
        packageName = "core/third-party/kaldi-native-fbank",
        version = "1.22.3 · Moonshine 0.1.5 vendored source",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine 네이티브 음성 특징 추출 구성입니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/core/third-party/kaldi-native-fbank/LICENSE",
        offlineDocumentAsset = "licenses/MOONSHINE-KALDI-NATIVE-FBANK-APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-kissfft",
        name = "Moonshine native · kissfft",
        packageName = "core/third-party/kissfft",
        version = "v131.1.0 · commit febd4caeed32e33ad8b2e0bb5ea77542c40f18ec · Moonshine 0.1.5 subset",
        licenseName = "BSD-3-Clause",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine v0.1.5 COPYING의 Mark Borgerding 저작권문과 pinned upstream BSD-3-Clause 전문을 함께 제공합니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/core/third-party/kissfft/COPYING",
        offlineDocumentAsset = "licenses/MOONSHINE-KISSFFT-NOTICE-AND-LICENSE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-json",
        name = "Moonshine native · nlohmann/json",
        packageName = "core/third-party/nlohmann",
        version = "3.11.3 · Moonshine 0.1.5 single-header subset",
        licenseName = "MIT License",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine 네이티브 JSON 구성의 원문 고지입니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/core/third-party/nlohmann/LICENSE.MIT",
        offlineDocumentAsset = "licenses/MOONSHINE-NLOHMANN-MIT.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-utf8cpp",
        name = "Moonshine native · utf8cpp",
        packageName = "core/third-party/utf-8",
        version = "Moonshine 0.1.5 vendored snapshot · upstream revision 미기록",
        licenseName = "Boost Software License 1.0",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine 네이티브 UTF-8 처리 구성의 원문 고지입니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/core/third-party/utf-8/LICENSE.txt",
        offlineDocumentAsset = "licenses/MOONSHINE-UTF8CPP-BSL-1.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-utf8proc",
        name = "Moonshine native · utf8proc",
        packageName = "core/third-party/utf8proc",
        version = "2.9.0 · Moonshine 0.1.5 vendored source",
        licenseName = "MIT License · Unicode data notice",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine 네이티브 Unicode 처리 구성과 데이터 고지입니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/core/third-party/utf8proc/LICENSE.md",
        offlineDocumentAsset = "licenses/MOONSHINE-UTF8PROC-MIT-UNICODE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-cpp-annote",
        name = "Moonshine native · cpp-annote data provenance",
        packageName = "embedded community-1 PLDA/config",
        version = "Moonshine 0.1.5 vendored source/data",
        licenseName = "CC BY 4.0 model-data attribution",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Embedded community-1 PLDA/config provenance is attributed to pyannote.ai under CC BY 4.0; downloaded diarization ONNX models are not part of the default GuideCast path.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/tree/v0.1.5/core/cpp-annote",
        offlineDocumentAsset = "licenses/MOONSHINE-CPP-ANNOTE-README.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-cpp-annote-code",
        name = "Moonshine native · cpp-annote code",
        packageName = "core/cpp-annote",
        version = "Moonshine 0.1.5 vendored source",
        licenseName = "MIT License",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine에 포함된 speaker-identification C++ 코드의 저작권·허가문입니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/core/cpp-annote/LICENSE",
        offlineDocumentAsset = "licenses/MOONSHINE-CPP-ANNOTE-MIT.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-native-silero-vad",
        name = "Moonshine native · Silero VAD",
        packageName = "embedded Silero VAD data",
        version = "commit b163605b · Moonshine 0.1.5 pinned",
        licenseName = "MIT License",
        category = LicenseCategory.AI_RUNTIME,
        notice = "Moonshine의 음성 구간 감지에 포함된 고정 Silero VAD 구성입니다.",
        sourceUrl = "https://github.com/snakers4/silero-vad/blob/b163605b3f44c3aadf28f97b125a2f7c461e9a7f/LICENSE",
        offlineDocumentAsset = "licenses/SILERO-VAD-PINNED-MIT.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "gemma-model",
        name = "Gemma 4 E2B IT LiteRT-LM",
        packageName = "litert-community/gemma-4-E2B-it-litert-lm",
        version = "gemma-4-E2B-it.litertlm · revision 6e5c4f1e395deb959c494953478fa5cec4b8008f",
        licenseName = "Apache License 2.0 (Gemma 4)",
        category = LicenseCategory.MODEL_AND_VOICE,
        notice = "APK와 분리해 사용자가 내려받는 고급 번역 모델입니다. 다운로드 소스는 표시된 immutable revision에 고정하고 Gemma 4 라이선스 전문을 APK에도 포함합니다.",
        sourceUrl = "https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/6e5c4f1e395deb959c494953478fa5cec4b8008f/gemma-4-E2B-it.litertlm",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "gemma-gpu-model",
        name = "Gemma 4 E2B GPU 최적화형 (시험용)",
        packageName = "litert-community/gemma-4-E2B-it-litert-lm",
        version = "gemma-4-E2B-it-gpu.litertlm · revision 6b78abd019e61a1ca4cbe3b212d2c9ce8ff38a94",
        licenseName = "Apache License 2.0 (Gemma 4)",
        category = LicenseCategory.MODEL_AND_VOICE,
        notice = "별도 다운로드하는 GPU 비교용 파일입니다. 기본형도 모바일 양자화 계열이며 이 선택지가 별개의 새 QAT 학습 모델임을 의미하지 않습니다. 단말별 품질·속도·메모리 개선은 미검증입니다.",
        sourceUrl = "https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/blob/6b78abd019e61a1ca4cbe3b212d2c9ce8ff38a94/gemma-4-E2B-it-gpu.litertlm",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "moonshine-korean-stt",
        name = "Moonshine Korean TINY STT",
        packageName = "ko · TINY · legacy non-streaming model",
        version = "Moonshine Voice 0.1.5 catalog",
        licenseName = "Moonshine AI Community License",
        category = LicenseCategory.MODEL_AND_VOICE,
        notice = "한국어 음성인식 모델입니다. 배포·상업 사용 시 공식 계약의 등록, 매출 기준, 계약 전문 제공과 표시 의무를 확인해야 합니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/blob/v0.1.5/LICENSE",
        offlineDocumentAsset = "licenses/MOONSHINE-0.1.5-LICENSE.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "kokoro-voices",
        name = "Kokoro 82M 음성",
        packageName = "af_heart · jf_alpha · zf_xiaoxiao",
        version = "Moonshine Voice 0.1.5 고정 manifest",
        licenseName = "Apache-2.0 · 언어별 G2P/사전 조건",
        category = LicenseCategory.MODEL_AND_VOICE,
        notice = "Kokoro 본체·voice tensor·ONNX는 Apache-2.0입니다. 영어 CMUdict 고지, 일본어 G2P의 CC-BY-SA-4.0 및 EDICT/ipa-dict의 CC-BY-SA-3.0, 중국어 G2P의 Apache-2.0 및 사전 원자료의 Unicode License/CC-BY-3.0도 적용됩니다.",
        sourceUrl = "https://github.com/moonshine-ai/moonshine/tree/v0.1.5/core/moonshine-tts/data",
        offlineDocumentAsset = "licenses/MODEL-AND-VOICE-NOTICES.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "piper-dutch-voice",
        name = "Piper Dutch MLS Medium",
        packageName = "piper_nl_NL-mls-medium",
        version = "Moonshine Voice 0.1.5 고정 manifest",
        licenseName = "MIT 저장소 · MLS CC-BY-4.0 · Dutch ipa-dict CC-BY",
        category = LicenseCategory.MODEL_AND_VOICE,
        notice = "Piper voice 저장소 메타는 MIT이고, 모델 카드가 밝힌 학습 데이터 MLS에는 CC-BY-4.0, Dutch INT ipa-dict에는 버전이 명시되지 않은 CC-BY 조건이 적용됩니다.",
        sourceUrl = "https://huggingface.co/rhasspy/piper-voices/tree/main/nl/nl_NL/mls/medium",
        offlineDocumentAsset = "licenses/MODEL-AND-VOICE-NOTICES.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "piper-spanish-voice",
        name = "Piper Spanish ALD Medium",
        packageName = "piper_es_MX-ald-medium",
        version = "Moonshine Voice 0.1.5 고정 manifest · 22,050 Hz",
        licenseName = "MIT 저장소 · ALD Unlicense · davefx CC0",
        category = LicenseCategory.MODEL_AND_VOICE,
        notice = "Moonshine 0.1.5가 실제 배포하는 멕시코 스페인어 스트리밍 음성입니다. Piper 저장소는 MIT, ALD 학습 데이터는 Unlicense이며 모델 카드가 밝힌 기반 davefx 데이터는 CC0입니다.",
        sourceUrl = "https://huggingface.co/rhasspy/piper-voices/tree/39ab474be869e9181350af6a65e4953eef67aaa0/es/es_MX/ald/medium",
        offlineDocumentAsset = "licenses/MODEL-AND-VOICE-NOTICES.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "piper-arabic-voice",
        name = "Piper Arabic Kareem Medium",
        packageName = "piper_ar_JO-kareem-medium · arabertv02_tashkeel_fadel · dict.tsv",
        version = "Moonshine Voice 0.1.5 고정 manifest · 22,050 Hz",
        licenseName = "MIT 저장소 · 학습 데이터/G2P 권리 미명시",
        category = LicenseCategory.MODEL_AND_VOICE,
        notice = "Moonshine 0.1.5 아랍어 음성에는 Kareem 모델, AraBERTv0.2 tashkeel 파생물과 CAMeL 기반 사전이 함께 필요합니다. Piper 저장소는 MIT이지만 음성 학습 데이터 저장소와 diacritizer checkpoint는 명시적 라이선스를 제공하지 않아 판매 전 별도 권리 확인이 필요합니다.",
        sourceUrl = "https://huggingface.co/rhasspy/piper-voices/tree/39ab474be869e9181350af6a65e4953eef67aaa0/ar/ar_JO/kareem/medium",
        offlineDocumentAsset = "licenses/MODEL-AND-VOICE-NOTICES.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "gradle-toolchain",
        name = "Gradle · Android Gradle Plugin",
        packageName = "Gradle · com.android.application/library",
        version = "8.13 · AGP 8.13.2",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.BUILD_AND_TEST,
        notice = "APK에는 포함되지 않는 빌드 도구입니다.",
        sourceUrl = "https://github.com/gradle/gradle",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "kotlin-toolchain",
        name = "Kotlin · Compose Compiler Plugin",
        packageName = "org.jetbrains.kotlin.android · org.jetbrains.kotlin.plugin.compose",
        version = "2.3.21",
        licenseName = "Apache License 2.0",
        category = LicenseCategory.BUILD_AND_TEST,
        notice = "APK에는 포함되지 않는 컴파일러와 Compose 빌드 플러그인입니다.",
        sourceUrl = "https://github.com/JetBrains/kotlin",
        offlineDocumentAsset = "licenses/APACHE-2.0.txt",
    ),
    ThirdPartyLicenseEntry(
        id = "android-test-toolchain",
        name = "JUnit · AndroidX Test · UI Automator",
        packageName = "junit · runner · ext-junit · uiautomator",
        version = "4.13.2 · 1.6.2 · 1.2.1 · 2.3.0",
        licenseName = "Eclipse Public License 1.0 · Apache License 2.0",
        category = LicenseCategory.BUILD_AND_TEST,
        notice = "APK에는 포함되지 않는 단위·에뮬레이터 시험 도구입니다. JUnit에는 EPL 1.0이, AndroidX Test에는 Apache-2.0이 적용됩니다.",
        sourceUrl = "https://github.com/junit-team/junit4/blob/r4.13.2/LICENSE-junit.txt",
    ),
)

internal fun filteredLicenseCatalog(
    query: String,
    category: LicenseCategory?,
): List<ThirdPartyLicenseEntry> {
    val normalizedQuery = query.trim().lowercase()
    return GUIDECAST_LICENSE_CATALOG.filter { entry ->
        (category == null || entry.category == category) &&
            (normalizedQuery.isEmpty() || listOf(
                entry.name,
                entry.packageName,
                entry.version,
                entry.licenseName,
                entry.notice,
            ).any { normalizedQuery in it.lowercase() })
    }
}
